<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>WinExe</OutputType>
		<TargetFramework>net10.0-windows</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<UseWPF>true</UseWPF>
		<RootNamespace></RootNamespace>
	</PropertyGroup>

	<ItemGroup>
		<Resource Include="Resources\Fonts\icon-basics\font\icon-basics.ttf" />
		<EmbeddedResource Include="Resources\Fonts\icon-media-control\config.json" />
		<Resource Include="Resources\Fonts\icon-media-control\font\icon-media-control.ttf" />
	</ItemGroup>
	
	<!-- Debug uses local project references -->
	<ItemGroup Condition="'$(Configuration)' == 'Debug'">
		<ProjectReference Include="..\IVSoftware.GlyphProvider.Portable\IVSoftware.GlyphProvider.Portable.csproj" />
	</ItemGroup>

	<ItemGroup Condition="'$(Configuration)' == 'Release'">
		<PackageReference Include="IVSoftware.GlyphProvider.Portable" Version="1.0.0-alpha" />
	</ItemGroup>

</Project>
